FROM php:7.4-apache

RUN docker-php-ext-install pdo_mysql

COPY ./app /var/www/html

# Enable mod_rewrite
RUN a2enmod rewrite

# Copy virtual host configuration
COPY apache-config/app.conf /etc/apache2/sites-available/app.conf
COPY apache-config/api.conf /etc/apache2/sites-available/api.conf

# Enable the virtual hosts
RUN a2ensite app.conf
RUN a2ensite api.conf

# Restart Apache
RUN service apache2 restart

# Expose port 80
EXPOSE 80
